apiVersion: batch/v1
kind: Job
metadata:
  name: encoder-outcome-prediction-icd10-icu-agent
  labels:
    app: encoder-outcome-prediction
spec:
  template:
    metadata:
      labels:
        app: encoder-outcome-prediction
    spec:
      containers:
        - name: encoder-outcome-prediction
          image: registry.datexis.com/tsteffek/encoderoutcomeprediction:2c034a1
          command: [
              "wandb", "agent",
              "--count", "10",
              "datexis-phd/EncoderOutcomePrediction/cqr9vyu2"
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: HF_HOME
              value: "/pvc/huggingface_cache"
            - name: WANDB_ENTITY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: entity
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api_key
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: eod-pvc
              mountPath: /data-pvc
            - name: eod-model-pvc
              mountPath: /model-pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: eod-pvc
          persistentVolumeClaim:
            claimName: eod-pvc
        - name: eod-model-pvc
          persistentVolumeClaim:
            claimName: large-eod-model-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
