apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
    containers:
    - image: busybox
      name: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
      - mountPath: /data-pvc
        name: data
      - mountPath: /model-pvc
        name: model-pvc
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: eod-pvc
      - name: model-pvc
        persistentVolumeClaim:
          claimName: eod-model-pvc
    restartPolicy: Never
