apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eod-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: shared

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eod-model-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: shared
