apiVersion: v1
kind: Pod
metadata:
  name: debug-shell
  namespace: s90444
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: ubuntu
      command: [ "sleep", "infinity" ]
      volumeMounts:
        - mountPath: /data-pvc
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: eod-pvc
