apiVersion: batch/v1
kind: Job
metadata:
  name: encoder-outcome-prediction-icd10-hosp
  labels:
    app: encoder-outcome-prediction
spec:
  template:
    metadata:
      labels:
        app: encoder-outcome-prediction
    spec:
      containers:
        - name: encoder-outcome-prediction
          image: registry.datexis.com/tsteffek/encoderoutcomeprediction:1145eb1
          command: [
              "python", "classification_main.py",
              "fit",
              "--trainer.accelerator=gpu",
              "--trainer.devices=1",
              "--trainer.precision=bf16",
              "--trainer.default_root_dir=/pvc/logs/PubMedBERT",
              "--trainer.min_epochs=30",
              "--trainer.callbacks+=EarlyStopping",
              "--trainer.callbacks.patience=10",
              "--trainer.callbacks.mode=min",
              "--trainer.callbacks.monitor=Val/Loss",
              "--trainer.callbacks+=ModelCheckpoint",
              "--trainer.callbacks.dirpath=/pvc/PubMedBERT",
              "--trainer.callbacks.filename=checkpoint",
              "--trainer.callbacks.save_top_k=1",
              "--trainer.callbacks.save_last=True",
              "--trainer.callbacks.mode=min",
              "--trainer.callbacks.monitor=Val/Loss",
              "--trainer.logger=WandbLogger",
              "--trainer.logger.project=EncoderOutcomePred",
              "--trainer.logger.anonymous=True",
              "--data.num_workers=16",
              "--data.eval_batch_size=128",
              "--data.batch_size=32",
              "--data.tokenizer=microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract",
              "--model.encoder_model_name=microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract",
              "--model.warmup_steps=150",
              "--model.decay_steps=20000",
              "--model.lr=2e-5",
              "--seed_everything=42",
              "--data.data_dir=/pvc/data/MIMIC-IV-LLM-Outcome/icd-10/hosp/",
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: HF_HOME
              value: "/pvc/huggingface_cache"
            - name: WANDB_ENTITY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: entity
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api_key
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: eod-pvc
              mountPath: /pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: eod-pvc
          persistentVolumeClaim:
            claimName: eod-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
