apiVersion: batch/v1
kind: Job
metadata:
  name: encoder-outcome-prediction-icd9-hosp
  labels:
    app: encoder-outcome-prediction
spec:
  template:
    metadata:
      labels:
        app: encoder-outcome-prediction
    spec:
      containers:
        - name: encoder-outcome-prediction
          image: registry.datexis.com/tsteffek/encoderoutcomeprediction:1858786
          command:
            - "python"
            - "classification_main.py"
            - "fit"
            - "--config=config.yaml"
            - "--trainer.default_root_dir=/data-pvc/icd9-icu"
            - "--data.data_dir=/pvc/data/mimic-iv/icd-9/icu/"
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: HF_HOME
              value: "/pvc/huggingface_cache"
            - name: WANDB_ENTITY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: entity
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api_key
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: eod-pvc
              mountPath: /data-pvc
            - name: eod-model-pvc
              mountPath: /model-pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: eod-pvc
          persistentVolumeClaim:
            claimName: eod-pvc
        - name: eod-model-pvc
          persistentVolumeClaim:
            claimName: large-eod-model-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
