command:
  - ${env}
  - "python"
  - "classification_main.py"
  - "fit"
  - "--config=config.yaml"
  - "--trainer.default_root_dir=/model-pvc/icd9-hosp"
  - "--trainer.max_epochs=20"
  - "--data.data_dir=/data-pvc/data/mimic-iv/icd9/hosp/"
  - "--data.pretrained_model=kamalkraj/distilBioBERT"
  - ${args}
method: bayes
metric:
  name: Val/AUROC
  goal: maximize
parameters:
  model:
    parameters:
      lr:
        min: 1e-6
        max: 1e-3
        distribution: log_uniform
      warmup_steps:
        min: 0
        max: 5000
      weight_decay:
        min: 1e-4
        max: 0.1
        distribution: log_uniform
      decay_steps:
        values: [10000, 20000, 30000, 40000, 50000]
  data:
    parameters:
      batch_size:
        values: [16, 32, 64, 128]