apiVersion: batch/v1
kind: Job
metadata:
  name: encoder-outcome-prediction-icd9-hosp-agent
  labels:
    app: encoder-outcome-prediction
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: encoder-outcome-prediction
    spec:
      containers:
        - name: encoder-outcome-prediction
          image: registry.datexis.com/tsteffek/encoderoutcomeprediction:distilbert
          command: [
              "wandb", "agent",
              "--count", "10",
              "datexis-phd/EncoderOutcomePred/5xx1yyfx"
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: HF_HOME
              value: "/model-pvc/huggingface_cache"
            - name: WANDB_ENTITY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: entity
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api_key
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: data-pvc
              mountPath: /data-pvc
            - name: model-pvc
              mountPath: /model-pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: data-pvc
          persistentVolumeClaim:
            claimName: eod-pvc
        - name: model-pvc
          persistentVolumeClaim:
            claimName: large-eod-model-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never