# lightning.pytorch==2.3.3
seed_everything: 42


trainer:
  accelerator: gpu
  strategy: auto
  devices: '1'
  num_nodes: 1
  precision: bf16-mixed
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: /model-pvc
      project: EncoderOutcomePred
      log_model: false
  callbacks:
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: Val/AUROC
      min_delta: 0.0
      patience: 10
      verbose: false
      mode: max
      strict: true
      check_finite: true
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: epoch={epoch}-valauroc={Val/AUROC:.2f}
      monitor: Val/AUROC
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: max
      auto_insert_metric_name: false
      enable_version_counter: true


  fast_dev_run: false
  max_epochs: 20
  num_sanity_val_steps: 0
  log_every_n_steps: 10
  accumulate_grad_batches: 1
  inference_mode: true
  use_distributed_sampler: true
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: /model-pvc


model:
  warmup_steps: 0
  decay_steps: 50000
  weight_decay: 0.01
  lr: 2.0e-05


data:
  data_dir: /data-pvc/MIMICIV/icd9/icu
  batch_size: 4
  eval_batch_size: 128
  pretrained_model: kamalkraj/distilBioBERT
  num_workers: 16
  truncate_again: true

  
ckpt_path: null
